config/routes.rb
Rails.application.routes.draw do
  resources :contactos
  resources :people
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "people#index"

  get 'contacto/', to: 'contactos#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contacto.rb
class Contacto < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contactos_controller.rb
class ContactosController < ApplicationController
  before_action :set_contacto, only: %i[ show edit update destroy ]

  # GET /contactos or /contactos.json
  def index
    @contactos = Contacto.all
  end

  # GET /contactos/1 or /contactos/1.json
  def show
  end

  # GET /contactos/new
  def new
    @contacto = Contacto.new
  end

  # GET /contactos/1/edit
  def edit
  end

  # POST /contactos or /contactos.json
  def create
    @contacto = Contacto.new(contacto_params)

    respond_to do |format|
      if @contacto.save
        format.html { redirect_to contacto_url(@contacto), notice: "Contacto was successfully created." }
        format.json { render :show, status: :created, location: @contacto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contacto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contactos/1 or /contactos/1.json
  def update
    respond_to do |format|
      if @contacto.update(contacto_params)
        format.html { redirect_to contacto_url(@contacto), notice: "Contacto was successfully updated." }
        format.json { render :show, status: :ok, location: @contacto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contacto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contactos/1 or /contactos/1.json
  def destroy
    @contacto.destroy

    respond_to do |format|
      format.html { redirect_to contactos_url, notice: "Contacto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contacto
      @contacto = Contacto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contacto_params
      params.require(:contacto).permit(:nombre, :correo, :comentario)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or /people.json
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to person_url(@person), notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to person_url(@person), notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:nombre, :correo, :perfil, :ocupacion)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contactos_helper.rb
module ContactosHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/contactos/_contacto.html.erb
<div id="<%= dom_id contacto %>">
  <p>
    <strong>Nombre:</strong>
    <%= contacto.nombre %>
  </p>

  <p>
    <strong>Correo:</strong>
    <%= contacto.correo %>
  </p>

  <p>
    <strong>Comentario:</strong>
    <%= contacto.comentario %>
  </p>

</div>

app/views/contactos/_form.html.erb
<%= form_with(model: contacto) do |form| %>
  <% if contacto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contacto.errors.count, "error") %> prohibited this contacto from being saved:</h2>

      <ul>
        <% contacto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :correo, style: "display: block" %>
    <%= form.text_field :correo %>
  </div>

  <div>
    <%= form.label :comentario, style: "display: block" %>
    <%= form.text_area :comentario %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contactos/edit.html.erb
<h1>Editing contacto</h1>

<%= render "form", contacto: @contacto %>

<br>

<div>
  <%= link_to "Ver este contacto", @contacto %> |
  <%= link_to "Volver a contactos", contactos_path %>
</div>

app/views/contactos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Contactos</h1>

<div id="contactos">
  <% @contactos.each do |contacto| %>
    <%= render contacto %>
    <p>
      <%= link_to "Ver este contacto", contacto %>
    </p>
  <% end %>
</div>

<%= link_to "Nuevo contacto", new_contacto_path %>

app/views/contactos/new.html.erb
<h1>Nuevo contacto</h1>

<%= render "form", contacto: @contacto %>

<br>

<div>
  <%= link_to "Volver a contactos", contactos_path %>
</div>

app/views/contactos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @contacto %>

<div>
  <%= link_to "Editar este contacto", edit_contacto_path(@contacto) %> |
  <%= link_to "Volver a contactos", contactos_path %>

  <%= button_to "Eliminar este contacto", @contacto, method: :delete %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #ccccb3;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <%# <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li> %>

        <li> <%= link_to "Contacto", new_contacto_path, class: "nav-link" %> </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :correo, style: "display: block" %>
    <%= form.text_field :correo %>
  </div>

  <div>
    <%= form.label :perfil, style: "display: block" %>
    <%= form.text_area :perfil %>
  </div>

  <div>
    <%= form.label :ocupacion, style: "display: block" %>
    <%= form.text_area :ocupacion %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/people/_person.html.erb
<div id="<%= dom_id person %>">
  <p>
    <strong>Nombre:</strong>
    <%= person.nombre %>
  </p>

  <p>
    <strong>Correo:</strong>
    <%= person.correo %>
  </p>

  <p>
    <strong>Perfil:</strong>
    <%= person.perfil %>
  </p>

  <p>
    <strong>Ocupacion:</strong>
    <%= person.ocupacion %>
  </p>

</div>

app/views/people/edit.html.erb
<h1>Editando persona</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Ver esta persona", @person %> |
  <%= link_to "Volver a personas, people_path %>
</div>

app/views/people/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Blog</h1>

<div id="people">
  <% @people.each do |person| %>
    <%= render person %>
    <p>
      <%= link_to "Ver esta persona", person %>
    </p>
  <% end %>
</div>

<%= link_to "Nueva persona", new_person_path %>

app/views/people/new.html.erb
<h1>Blog</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Volver a personas", people_path %>
</div>

app/views/people/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @person %>

<div>
  <%= link_to "Editar esta persona", edit_person_path(@person) %> |
  <%= link_to "Volver a personas", people_path %>

  <%= button_to "Eliminar esta persona", @person, method: :delete %>
</div>